### ISSUE TITLE
o.c.r.PropertiesFileRuleSetConfigurer -- RuleSet configuration properties file [codenarc.properties] not found.

### ISSUE THREAD

**Issue by harishjangam6979** [nvuillam/npm-groovy-lint#345] opened 2023-12-18 06:58 UTC
I've recently upgraded my npm-lint version from 9 to 13. However, i'm facing the below issue when running the npm-groovy-lint command.

```
+ npm-groovy-lint --noserver
GroovyLint: Error running CodeNarc: 
22:57:47.254 [main] INFO  o.c.r.PropertiesFileRuleRegistry -- Loaded properties file in 300ms; 397 rules
22:57:59.960 [main] INFO  o.c.r.PropertiesFileRuleSetConfigurer -- RuleSet configuration properties file [codenarc.properties] not found.
```
My .groovylintrc.json is below

```
{
  "extends": "all",
  "rules": {
    "basic.DeadCode": "error",
    "convention.CompileStatic": {
      "severity": "info"
    },
    "convention.FieldTypeRequired": "info",
    "convention.IfStatementCouldBeTernary": "info",
    "convention.NoDef": "info",
    "convention.TrailingComma": "off",
    "convention.VariableTypeRequired": "info",
    "dry.DuplicateListLiteral": "info",
    "dry.DuplicateMapLiteral": "warning",
    "dry.DuplicateNumberLiteral": {
      "ignoreNumbers": [0, 1, 2, 3, -1],
      "severity": "info"
    },
    "dry.DuplicateStringLiteral": "info",
    "exceptions.ThrowException": "info",
    "exceptions.ThrowNullPointerException": "info",
    "exceptions.ThrowRuntimeException": "info",
    "exceptions.ThrowThrowable": "info",
    "formatting.BracesForClass": "info",
    "formatting.BracesForForLoop": "info",
    "formatting.BracesForIfElse": "info",
    "formatting.BracesForMethod": "info",
    "formatting.BracesForTryCatchFinally": "info",
    "formatting.Indentation": {
      "spacesPerIndentLevel": 4,
      "severity": "info"
    },
    "formatting.SpaceAroundMapEntryColon": "off",
    "groovyism.ExplicitCallToEqualsMethod": "info",
    "logging.Println": "off",
    "unused.UnusedArray": "error",
    "unused.UnusedObject": "error",
    "unused.UnusedPrivateField": "error",
    "unused.UnusedPrivateMethod": "error",
    "unused.UnusedPrivateMethodParameter": "error",
    "unused.UnusedVariable": "error",
    "unnecessary.UnnecessaryReturnKeyword": "off"
  }
}
```
I tried adding codenarc.properties file with ruleset=org.codenarc.ruleset.AllRules as data in it. Still the issue persist.

@nvuillam

**Comment by nvuillam** [comment] 2023-12-18 08:26
@harishjangam6979 it seems to be an output from CodeNarc... 

Do you have a sample repo where we could reproduce it ?

cc @stevenh

**Comment by nvuillam** [comment] 2023-12-18 08:27
Note: 14.0.0 has been released and contains again more refactoring, please can you upgrade from 13 to 14 to see if the issue persists ?

https://github.com/nvuillam/npm-groovy-lint/releases/tag/v14.0.0

**Comment by stevenh** [comment] 2023-12-18 12:42
I don't think that's anything to worry about, previously this could well have been hidden but with the new logging setup you'll see INFO and above both `npm-groovy-lint` and `CodeNarc`.

Are you seeing any adverse effects?

**Comment by stevenh** [comment] 2023-12-18 12:59
Closing as duplicate of https://github.com/nvuillam/npm-groovy-lint/issues/342

**Closed by stevenh** 2023-12-18 12:59 UTC
